<!doctype html>
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>LoL Power Rankings</title>
		<meta name="description" content="Community powered League of Legends power rankings">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" href="css/normalize.css">
		<link rel="stylesheet" href="css/main.css">

		<script src="js/vendor/modernizr-2.8.3.min.js"></script>
	</head>
	<body>
		<!--[if lt IE 8]>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->
		<nav id="navigation">
			<a href="eulcs.php" title="LCS EU">LCS EU</a>
			<a href="nalcs.php" title="LCS NA">LCS NA</a></li>
			<a href="user.php" title="Your rankings" class="nav-right">Test</a></li>
		</nav>
		<main class="main-container standings">
			<header class="standings-header">
				<h1><?php echo $test ?></h1>
			</header>
			<section id="sortable-container" class="standings-ranking">
				<div class="team-row" data-id="g2esports">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/gamers2-b08he8l4.png&amp;resize=100:100" alt="G2 Esports">
					</div>
					<div class="team-name">
						G2 Esports
					</div>
				</div>
				<div class="team-row" data-id="uol">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/unicorns-of-love-acxt0jy4.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						Unicorns of Love
					</div>
				</div>
				<div class="team-row" data-id="fnatic">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/fnatic-1jz4gx6t.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						Fnatic
					</div>
				</div>
				<div class="team-row" data-id="elements">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/elements-hl4t97vj.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						Elements
					</div>
				</div>
				<div class="team-row" data-id="h2k">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/h2k-809eyzf8.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						H2k
					</div>
				</div>
				<div class="team-row" data-id="origen">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/origen-2wse5ns8.png&resize=100:100" alt="G2 Esports">
					</div>
					<div class="team-name">
						Origen
					</div>
				</div>
				<div class="team-row" data-id="splyce">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/splyce-81ipjuao.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						Splyce
					</div>
				</div>
				<div class="team-row" data-id="vitality">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/vitality-9z83n51v.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						Team Vitality
					</div>
				</div>
				<div class="team-row" data-id="roccat">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/roccat-3rt7loly.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						Team ROCCAT
					</div>
				</div>
				<div class="team-row" data-id="giants">
					<div class="team-logo">
						<img src="http://am-a.akamaihd.net/image/?f=http://assets.lolesports.com/team/giants-gaming-aji5fbac.png&resize=100:100" alt="H2k">
					</div>
					<div class="team-name">
						Giants
					</div>
				</div>
			</section>
		</main>

		<script src="js/vendor/Sortable.min.js"></script>
		<script src="js/main.js"></script>
	</body>
</html>
