<?php include('includes/header.php'); ?>
	<body>
		<!--[if lt IE 8]>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->
		<?php include('includes/navigation.php'); ?>
		<main class="main-container standings">
			<header class="standings-header">
				<h1><?php echo $test ?></h1>
			</header>
			<section id="sortable-container" class="standings-ranking">
				<?php foreach ($teams as $team) { ?>
					<div class="team-row" data-id="<?= $team['short']; ?>">
						<div class="team-logo">
							<img src="<?= $local ?>img/logos/<?= $team['logo']; ?>" alt="<?= $team['name']; ?>">
						</div>
						<div class="team-name">
							<?= $team['name']; ?>
						</div>
					</div>
				<?php } ?>
			</section>
		</main>
		<?php include('includes/closure.php'); ?>
	</body>
</html>
